// Group: Momtrimo
 // File: Jenkinsfile
 // Description: To define CI/CD pipeline for Docker Image Buliding and pushing, deploying to Kubernetes cluster

pipeline {
    agent any

    environment {
        DOCKERHUB_PASS = credentials('docker')
        BUILD_TIMESTAMP = new Date().format("yyyyMMdd-HHmmss", TimeZone.getTimeZone("UTC"))
    }

    stages {
        stage("Build & Package with Maven") {
            steps {
                script {
                    // Clone the repo
                    checkout scm

                    // Move into momtrimo folder then build
                    dir('momtrimo') {
                        sh 'mvn clean package'
                    }
                }
            }
        }

        stage("Build Docker Image") {
            steps {
                script {
                    // Docker login
                    sh '''
                      echo "$DOCKERHUB_PASS_PSW" | docker login -u gautam26 --password-stdin
                    '''
                    // Build inside the momtrimo folder
                    dir('momtrimo') {
                        sh "docker build -t gautam26/swe645:1.0-${BUILD_TIMESTAMP} ."
                    }
                }
            }
        }

        stage("Push Image to DockerHub") {
            steps {
                script {
                    sh "docker push gautam26/swe645:1.0-${BUILD_TIMESTAMP}"
                }
            }
        }

        stage("Deploy to Kubernetes") {
            steps {
                withCredentials([file(credentialsId: 'kubeconfig', variable: 'KUBECONFIG')]) {
                    sh "kubectl set image deployment/deployment-hw3 survey=gautam26/swe645:1.0-${BUILD_TIMESTAMP} -n default"
                }
            }
        }
    }
}
